# Generated by Django 5.2.6 on 2025-10-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homologacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('materia_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_destino', to='materias.materia')),
                ('materia_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_origen', to='materias.materia')),
            ],
        ),
    ]
