# Generated by Django 5.2.6 on 2025-10-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('universidad', models.CharField(max_length=255)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('procesada', models.BooleanField(default=False)),
            ],
        ),
    ]
