# Generated by Django 5.2.6 on 2025-10-16 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='procesada',
            new_name='embedding_generado',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='universidad',
        ),
        migrations.AddField(
            model_name='materia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
