# Generated by Django 5.2.6 on 2025-12-09 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('creditos', models.IntegerField()),
                ('contenido_tematico', models.TextField(help_text='Descripción detallada del contenido que Gemini usará para la comparación.')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homologador.carrera')),
            ],
        ),
    ]
