# Generated by Django 5.2.6 on 2025-12-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homologador', '0002_historicohomologacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicohomologacion',
            name='archivo_docx',
            field=models.FileField(blank=True, help_text='Documento DOCX generado de la homologación.', null=True, upload_to='homologaciones_docs/'),
        ),
    ]
