# Generated by Django 5.2.6 on 2025-12-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homologador', '0003_historicohomologacion_archivo_docx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicohomologacion',
            name='resultado_json',
        ),
    ]
