# Generated by Django 5.2.6 on 2025-12-15 20:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homologador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoHomologacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(blank=True, help_text='Nombre del estudiante (si se puede extraer).', max_length=200, null=True)),
                ('documento_identidad', models.CharField(blank=True, help_text='Cédula o ID del estudiante.', max_length=50, null=True)),
                ('resultado_json', models.TextField(help_text='Resultado completo de la homologación en formato JSON.')),
                ('fecha_procesamiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('archivo_pdf_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('carrera_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homologador.carrera')),
            ],
            options={
                'verbose_name': 'Histórico de Homologación',
                'verbose_name_plural': 'Históricos de Homologación',
                'ordering': ['-fecha_procesamiento'],
            },
        ),
    ]
